CREATE TABLE "produkt" (
	"id_produktu" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nazwa" TEXT NOT NULL,
	"cena" MONEY NOT NULL,
	PRIMARY KEY("id_produktu")
);


CREATE TABLE "sklep" (
	"id_sklepu" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nazwa_sklepu" VARCHAR(255) NOT NULL,
	"ulica" VARCHAR(255),
	PRIMARY KEY("id_sklepu")
);


CREATE TABLE "uzytkownicy" (
	"id_uzytkownika" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"imie" VARCHAR(255) NOT NULL,
	"nazwisko" VARCHAR(255),
	"administrator" BOOLEAN NOT NULL,
	"login" VARCHAR(255) NOT NULL,
	"haslo" VARCHAR(255) NOT NULL,
	"id_sklepu" SMALLINT NOT NULL,
	PRIMARY KEY("id_uzytkownika")
);


CREATE TABLE "sprzedaz" (
	"id_sprzedazy" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_sklepu" SMALLINT NOT NULL,
	"id_uzytkownika" SMALLINT NOT NULL,
	"kwota_transakcji" MONEY NOT NULL,
	"data_sprzedazy" DATE NOT NULL,
	PRIMARY KEY("id_sprzedazy")
);


CREATE TABLE "pozycja_sprzedazy" (
	"id_pozycji" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_sprzedazy" SMALLINT NOT NULL,
	"id_produktu" SMALLINT NOT NULL,
	"ilosc" SMALLINT NOT NULL,
	"cena_jednostkowa" MONEY NOT NULL,
	PRIMARY KEY("id_pozycji")
);


CREATE TABLE "stan_magazynowy" (
	"id_stanu" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_sklepu" SMALLINT NOT NULL,
	"id_produktu" SMALLINT NOT NULL,
	"ilosc" INTEGER NOT NULL,
	PRIMARY KEY("id_stanu")
);


CREATE TABLE "kuchnia" (
	"id_kuchni" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"ulica" VARCHAR(255),
	PRIMARY KEY("id_kuchni")
);


CREATE TABLE "jadlospis" (
	"id_jadlospisu" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_kuchni" SMALLINT,
	"id_firmy" SMALLINT,
	PRIMARY KEY("id_jadlospisu")
);

CREATE TABLE "pozycja_jadlospisu" (
	"id_pozycji_jadlospisu" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_jadlospisu" SMALLINT NOT NULL,
	"id_produktu" SMALLINT NOT NULL,
	PRIMARY KEY("id_pozycji_jadlospisu")
);


CREATE TABLE "zamowienie" (
	"id_zamowienia" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_sklepu" SMALLINT NOT NULL,
	"id_uzytkownika" SMALLINT,
	"data_zamowienia" DATE NOT NULL,
	"koszt_zamowienia" MONEY NOT NULL,
	"wczytane_do_stanu" BOOLEAN,
	PRIMARY KEY("id_zamowienia")
);


CREATE TABLE "pozycja_zamowienia" (
	"id_pozycji_zamowienia" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_zamowienia" SMALLINT NOT NULL,
	"id_pozycji_jadlospisu" SMALLINT NOT NULL,
	"ilosc_produktu" SMALLINT NOT NULL,
	PRIMARY KEY("id_pozycji_zamowienia")
);


CREATE TABLE "firma_zewnetrzna" (
	"id_firmy" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nazwa" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_firmy")
);


CREATE TABLE "oferta_firmy_zewnetrznej" (
	"id_oferty" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_firmy" SMALLINT NOT NULL,
	"id_produktu" SMALLINT,
	PRIMARY KEY("id_oferty")
);


ALTER TABLE "stan_magazynowy"
ADD FOREIGN KEY("id_produktu") REFERENCES "produkt"("id_produktu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "stan_magazynowy"
ADD FOREIGN KEY("id_sklepu") REFERENCES "sklep"("id_sklepu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "uzytkownicy"
ADD FOREIGN KEY("id_sklepu") REFERENCES "sklep"("id_sklepu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sprzedaz"
ADD FOREIGN KEY("id_sklepu") REFERENCES "sklep"("id_sklepu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pozycja_sprzedazy"
ADD FOREIGN KEY("id_sprzedazy") REFERENCES "sprzedaz"("id_sprzedazy")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pozycja_sprzedazy"
ADD FOREIGN KEY("id_produktu") REFERENCES "produkt"("id_produktu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "jadlospis"
ADD FOREIGN KEY("id_kuchni") REFERENCES "kuchnia"("id_kuchni")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pozycja_jadlospisu"
ADD FOREIGN KEY("id_produktu") REFERENCES "produkt"("id_produktu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pozycja_jadlospisu"
ADD FOREIGN KEY("id_jadlospisu") REFERENCES "jadlospis"("id_jadlospisu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "zamowienie"
ADD FOREIGN KEY("id_sklepu") REFERENCES "sklep"("id_sklepu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pozycja_zamowienia"
ADD FOREIGN KEY("id_zamowienia") REFERENCES "zamowienie"("id_zamowienia")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pozycja_zamowienia"
ADD FOREIGN KEY("id_pozycji_jadlospisu") REFERENCES "pozycja_jadlospisu"("id_pozycji_jadlospisu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sprzedaz"
ADD FOREIGN KEY("id_uzytkownika") REFERENCES "uzytkownicy"("id_uzytkownika")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "oferta_firmy_zewnetrznej"
ADD FOREIGN KEY("id_firmy") REFERENCES "firma_zewnetrzna"("id_firmy")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "oferta_firmy_zewnetrznej"
ADD FOREIGN KEY("id_produktu") REFERENCES "produkt"("id_produktu")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "jadlospis"
ADD FOREIGN KEY("id_firmy") REFERENCES "firma_zewnetrzna"("id_firmy")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "zamowienie"
ADD FOREIGN KEY("id_uzytkownika") REFERENCES "uzytkownicy"("id_uzytkownika")
ON UPDATE NO ACTION ON DELETE NO ACTION;